version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/examples/php-worker"
    schedule:
      interval: "daily"
    assignees:
      - "rustatian"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "rustatian"
