apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: roadrunner
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/roadrunner-server/k8s-examples.git
    targetRevision: master
    path: deploy/charts/roadrunner
    helm:
      valueFiles:
        - ../../argocd/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: roadrunner
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
