{{- if not .Values.roadrunner.existingConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "roadrunner.configMapName" . }}
  labels:
    {{- include "roadrunner.labels" . | nindent 4 }}
data:
  .rr.yaml: |
{{ tpl .Values.roadrunner.config . | indent 4 }}
{{- end }}
