{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "roadrunner.fullname" . }}
  labels:
    {{- include "roadrunner.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "roadrunner.selectorLabels" . | nindent 6 }}
  {{- if and (hasKey .Values.pdb "minAvailable") (ne .Values.pdb.minAvailable nil) }}
  minAvailable: {{ .Values.pdb.minAvailable }}
  {{- else if and (hasKey .Values.pdb "maxUnavailable") (ne .Values.pdb.maxUnavailable nil) }}
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}
  {{- end }}
{{- end }}
